enum SecurityColumns: String
{
    case secid = "SECID"
    case boardId = "BOARDID"
    case shortName = "SHORTNAME"
    case lotSize = "LOTSIZE"
    case setleDate = "SETTLEDATE"
    case decimals = "DECIMALS"
    case faceValue = "FACEVALUE"
    case marketCode = "MARKETCODE"
    case minStep = "MINSTEP"
    case prevDate = "PREVDATE"
    case secName = "SECNAME"
    case remarks = "REMARKS"
    case satus = "STATUS"
    case faceUnit = "FACEUNIT"
    case prevPrice = "PREVPRICE"
    case prevWaPrice = "PREVWAPRICE"
    case currencyId = "CURRENCYID"
    case latName = "LATNAME"
}
